SET MODE MYSQL;

CREATE schema IF NOT EXISTS `public`;

CREATE TABLE IF NOT EXISTS `public.SIMPLE_CALCULATION` (
  `ID` int NOT NULL,
  `LEFT_HAND` int DEFAULT NULL,
  `RIGHT_HAND` int DEFAULT NULL,
  `OPERATOR` varchar(255) DEFAULT NULL,
  `RESULT` int DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

truncate table `public.SIMPLE_CALCULATION`;



